# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPods
  pod 'Alamofire', '~> 4.7'
  pod "Unbox"
  pod 'Kingfisher', '~> 4.0'
  
end
  target 'CocoaPodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoaPodsUITests' do
    inherit! :search_paths
    # Pods for testing
  end


